/****************************************************************************
**
** Metadata for QCalculation generated by dumpcpp v5.11.2 using
** c:\program files\python\python37\lib\site-packages\pyqt5_tools\dumpcpp.exe {791d8177-81c2-4516-8347-38403ec944a5}
** from the type library C:\Users\Vu\Documents\PixylBooth\QCalculation.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_QCALCULATION_NOINLINES
#include "qcalculation.h"

using namespace QCalculation;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[24];
    char stringdata0[259];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 32, 0),
QT_MOC_LITERAL(1, 33, 9, 0),
QT_MOC_LITERAL(2, 43, 0, 0),
QT_MOC_LITERAL(3, 44, 4, 0),
QT_MOC_LITERAL(4, 49, 6, 0),
QT_MOC_LITERAL(5, 56, 4, 0),
QT_MOC_LITERAL(6, 61, 4, 0),
QT_MOC_LITERAL(7, 66, 15, 0),
QT_MOC_LITERAL(8, 82, 4, 0),
QT_MOC_LITERAL(9, 87, 6, 0),
QT_MOC_LITERAL(10, 94, 4, 0),
QT_MOC_LITERAL(11, 99, 4, 0),
QT_MOC_LITERAL(12, 104, 7, 0),
QT_MOC_LITERAL(13, 112, 23, 0),
QT_MOC_LITERAL(14, 136, 17, 0),
QT_MOC_LITERAL(15, 154, 15, 0),
QT_MOC_LITERAL(16, 170, 11, 0),
QT_MOC_LITERAL(17, 182, 18, 0),
QT_MOC_LITERAL(18, 201, 6, 0),
QT_MOC_LITERAL(19, 208, 3, 0),
QT_MOC_LITERAL(20, 212, 11, 0),
QT_MOC_LITERAL(21, 224, 7, 0),
QT_MOC_LITERAL(22, 232, 16, 0),
QT_MOC_LITERAL(23, 249, 8, 0)
    },
    "QCalculation::ComClass1Interface\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0control\0QCalculation::calculate\0Event Interface 2\0"
    "ComClass1Events\0Interface 1\0ComClass1Interface\0Equals\0obj\0GetHashCode\0GetType\0"
    "mscorlib::_Type*\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_QCalculation__ComClass1Interface[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    3, 14, // methods
    1, 48, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 29, 2, 5,
    7, 1, 38, 2, 5,
    9, 3, 41, 2, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

 // properties: name, type, flags
    12, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ComClass1Interface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_QCalculation__ComClass1Interface, 0, 0, 0 }
};

void *ComClass1Interface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "QCalculation::ComClass1Interface"))
        return static_cast<void*>(const_cast<ComClass1Interface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_QCalculation__calculate[] = {

 // content:
    7, // revision
    13,  // classname
    2, 14, // classinfo
    6, 18, // methods
    1, 72, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    14, 15, 
    16, 17, 

// signal: name, argc, parameters, tag, flags
    1, 4, 48, 2, 5,
    7, 1, 57, 2, 5,
    9, 3, 60, 2, 5,

// slot: name, argc, parameters, tag, flags
    18, 1, 67, 2, 9,
    20, 0, 70, 2, 9,
    21, 0, 71, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 19,
    QMetaType::Int,
    0x80000000 | 22,

 // properties: name, type, flags
    23, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject calculate::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_QCalculation__calculate, 0, 0, 0 }
};

void *calculate::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "QCalculation::calculate"))
        return static_cast<void*>(const_cast<calculate*>(this));
    return QAxObject::qt_metacast(_clname);
}

